Add option to set a specific supabase URL on the server side
nuxt-modules/supabase pull request #319
Opened 2023-12-24 19:09 UTC by jfoucher

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

This change adds a new configuration option: `serverUrl`. When set, it overrides the `url` option on the serverside only when using SSR.

A  problem can occur when using nuxt-supabase with SSR in a docker-compose environment. The browser will connect to supabase on the exposed port, e.g. localhost:8000 whereas the server side, running in docker will have to connect to e.g. `supabase:8000`
This PR allows for setting a different supabase server URL on the browser side and on the server side.

## Checklist:

- [x ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes (if not applicable, please state why)
I didn't see any tests in the source, nor a way to run any.

2023-12-27 09:54 UTC, Atinux commented on package.json
> +  "name": "jfoucher-nuxt-supabase",
You should not update the `package.json`

2023-12-27 09:58 UTC, Atinux commented
Could you please remove the update on the `package.json` and lock file?

Can you also update the documentation to explain about your new option? https://supabase.nuxtjs.org/get-started#options (https://github.com/nuxt-modules/supabase/edit/main/docs/content/2.get-started.md)

2023-12-28 10:28 UTC, larbish requested changes

2023-12-28 10:28 UTC, larbish commented on src/runtime/plugins/supabase.server.ts
> +    const supabaseClient = createClient(serverUrl ? serverUrl : url, key, options)
```suggestion
    const supabaseClient = createClient(serverUrl || url, key, options)
```

2023-12-28 10:28 UTC, larbish commented on src/runtime/server/services/serverSupabaseClient.ts
> +    supabaseClient = createClient(serverUrl ? serverUrl : url, key, options)
```suggestion
    supabaseClient = createClient(serverUrl || url, key, options)
```

2023-12-30 13:37 UTC, jfoucher commented on src/runtime/plugins/supabase.server.ts
> +    const supabaseClient = createClient(serverUrl ? serverUrl : url, key, options)
Fixed with the latest commit

2023-12-30 13:38 UTC, jfoucher commented
Requested changes have been made in https://github.com/nuxt-modules/supabase/pull/319/commits/941ef0ee45bb24e61e71b8fd6742faaaea9ce1e4

2024-07-05 10:56 UTC, closed without merging